import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='font-rubik bg-neutral-veryLightGray flex justify-center flex-col items-center'>
        {children}
      </body>
    </html>
  );
}
